apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: besuscan-prod
  labels:
    app: api
    environment: production
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: api 