apiVersion: v1
kind: Service
metadata:
  name: indexer-service
  namespace: besuscan-prod
  labels:
    app: indexer
    environment: production
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: indexer 