apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: besuscan-prod
  labels:
    app: besuscan
    component: rabbitmq
    environment: production
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: management
  selector:
    app: besuscan
    component: rabbitmq 