apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: besuscan-prod
  labels:
    app: besuscan
    component: redis
    environment: production
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: besuscan
    component: redis 