apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: besuscan-prod
  labels:
    app: worker
    environment: production
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: worker 