apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: besuscan-prod
  labels:
    app: besuscan
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: besuscan/api:v1.0.3
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: besuscan-app-secrets
              key: DATABASE_URL
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: besuscan-app-secrets
              key: RABBITMQ_URL
        - name: RABBITMQ_EXCHANGE
          valueFrom:
            configMapKeyRef:
              name: besuscan-app-config
              key: RABBITMQ_EXCHANGE
        - name: BESU_RPC_URL
          valueFrom:
            configMapKeyRef:
              name: besuscan-app-config
              key: BESU_RPC_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: besuscan-app-secrets
              key: REDIS_URL
        - name: CHAIN_ID
          valueFrom:
            configMapKeyRef:
              name: besuscan-app-config
              key: CHAIN_ID
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: besuscan-app-config
              key: API_PORT
        - name: ENABLE_WEBSOCKET
          valueFrom:
            configMapKeyRef:
              name: besuscan-app-config
              key: ENABLE_WEBSOCKET
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: besuscan-app-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m" 