apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: besuscan-prod
  labels:
    app: besuscan
    component: rabbitmq
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: besuscan
      component: rabbitmq
  template:
    metadata:
      labels:
        app: besuscan
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management-alpine
        ports:
        - containerPort: 5672  # AMQP
        - containerPort: 15672 # Management UI
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            configMapKeyRef:
              name: besuscan-app-config
              key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: besuscan-app-secrets
              key: RABBITMQ_PASSWORD
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-pvc 