root = "."
tmp_dir = "tmp"

[build]
  bin = "/tmp/main"
  cmd = "go build -o /tmp/main ./cmd/main.go"
  delay = 1000 # ms
  exclude_dir = ["assets", "tmp", "vendor"]
  follow_symlink = false
  full_bin = "/tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "2s"  # Aumentar tempo para graceful shutdown
  log = "build-errors.log"
  send_interrupt = true  # Enviar SIGINT primeiro
  stop_on_error = true

[log]
  time = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[output]
  log = "log.txt"

[runner]
  prepend_cmd = []
  args = []

[watcher]
  ignore = ["tmp", ".git"]
  # Reduzir frequência de polling para evitar rebuilds desnecessários
  poll = true
  poll_interval = 500
